### ISSUE TITLE
 no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by jon100p** [colinbourassa/rovergauge#21]
when trying to run the 32 bit version of version of 10.5 the error "failed to start because no Qt platform plugin could be initialized" happens.   (version 10.3 works OK).

**Comment by jon100p** [comment]
Dear Colin,

Thank you for your email.
I checked and the platforms folder and .dll file are there and I am running
32 bit windows.

I have tried extracting the files for the zip again to a different folder
and now the rovergauge opens without problems.   I don't know why this is
any different from before but all is OK now and I am a bit
embarrassed about posting it as a problem.

Sorry for wasting your time and many thanks for making the software
available.

regards,
Jon

**Comment by stevesprint** [comment]
Hi Colin

Sorry for the delayed reply, I wanted to re-test 32-bit RG on a 32-bit laptop and 64-bit RG on a 64-bit laptop and I can now confirm its an issue on both platforms, fuelMapIndex = 0 in static.txt when starting RG with –a –l options before cranking but with the ignition on.  Furthermore its only an issue when starting will all the inputs enable with the attached RoverGaugeAll.ini but not an issue with when auto starting with the attached StartLoggersHiRpm.ini

Its such a minor issue its not worth loosing sleep over especially as most people don’t switch maps like I do, these days I work on map 3 & copy my last good map to 2 in-case I suddenly need to go back.

Yes I’m running 0.10.5 32 & 64bit & qwindows.dll is in the platforms sub directors as follows;
32bit laptop - 1,617,408 byte  27/05/2020 11:57
64bit laptop - 1,695,232 byte 27/05/2020 12:56

Might be useful if possible to add 32bit or 64bit on the About window? but doesn’t really matter.

Cheers
Steve

**Comment by stevesprint** [comment]
Hi Colin

Sorry for the delayed reply, I wanted to re-test 32-bit RG on my 32-bit laptop and 64-bit RG on my 64-bit laptop and I can now confirm that on both platforms fuelMapIndex = 0 in static.txt when starting RG with –a –l options before cranking but with the ignition on before connecting.  Interestingly, its only an issue when starting with all the inputs enabled (with the attached RoverGaugeAll.ini) but not an issue when starting with the attached StartLoggersHiRpm.ini.  Furthermore, I’m sure you realise that when fuelMapIndex = 0 then fuelMapMultiplier is the default Multiplier, I assume because the code doesn’t know which map is in use yet.

Yes, qwindows.dll is in the platforms sub directors as follows;
32bit laptop - 1,617,408 byte  27/05/2020 11:57
64bit laptop - 1,695,232 byte 27/05/2020 12:56

Its such a minor issue its not worth loosing sleep over as most people generally don’t test different maps like I do & these days I tend to work on map 3 & copy my last good map to 2 in case I suddenly need to go back.  

I guess I’m asked more often why are the RPM limiter & multiplier incorrect on the main screen before cranking, I can image why but maybe you could considering loading the RPM limiter and multiplier directly from the prom.

It might be helpful if you can add 32bit or 64bit on the About window? but doesn’t really matter.

Thanks again for a brilliant 14CUX diagnostic tool.

Cheers
Steve
